#记得要设置本目录为资源配置目录
server:
  port: 8761

spring:
  application:
    name: springcloud-eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    #是否注册自身
    register-with-eureka: false
    #是否获取注册信息
    fetch-registry: false
    service-url:
      #注册服务地址
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #启用自我保护
    enable-self-preservation: true

endpoints:
  shutdown:
    enabled: true

logging:
  config: classpath:logback.xml