#记得要设置本目录为资源配置目录
server:
  port: 8763

spring:
  application:
    name: springcloud-eureka-server

eureka:
  instance:
    hostname: peer3
  client:
    #是否注册自身
    register-with-eureka: true
    #是否获取注册信息
    fetch-registry: true
    service-url:
      #注册服务地址
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  server:
    #启用自我保护
    enable-self-preservation: true

endpoints:
  shutdown:
    enabled: true

logging:
  config: classpath:logback-peer3.xml