#记得要设置本目录为资源配置目录

#端口
server:
  port: 1234

#应用信息
spring:
  application:
    name: springcloud-zuul-gateway

#注册中心
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

#日志
logging:
  config: classpath:logback.xml

#路由信息
zuul:
  routes:
    springcloud-ribbon-consumer:
      path: /ribbon/**
      service-id: springcloud-ribbon-consumer
    springcloud-feign-consumer:
      path: /feign/**
      service-id: springcloud-feign-consumer