#TODO 记得要设置本目录为资源配置目录
server:
  #服务端口
  port: 8888
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        health:
          enabled: true
        #配置仓库地址
        git:
          uri: https://github.com/mhq0123/spring-cloud-demo.git
          #{application} 动态搜索
          search-paths: springcloud-config-repository/{application}
          #启动时是否clone
          clone-on-start: true
        #多仓库配置
#        repos:
#          local-a:
#            pattern:
#              - */local-a*
#              - */local-a/*
#            uri: file:/home/config-repo/local-a/
#          local-b:
#            pattern:
#              - */local-b*
#              - */local-b/*
#            uri: file:/home/config-repo/local-b/

#开启用户名密码验证
security:
  user:
    role: whole
    name: user
    password: 123456
