spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mhq0123/spring-cloud-demo.git
          searchPaths: springcloud-config-repository/*
          cloneOnStart: true

server:
  port: 8888
