#记得要设置本目录为资源配置目录
server:
  port: 8121

spring:
  application:
    name: springcloud-service-internal-users

eureka:
  client:
    service-url:
      #注册服务地址
      default-zone: http://localhost:8761/eureka/

logging:
  config: classpath:logback.xml