#记得要设置本目录为资源配置目录
server:
  port: 8112

spring:
  application:
    name: springcloud-service-external-users

#注册服务
eureka:
  client:
    service-url:
      # TODO 注册中心集群
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/

#日志
logging:
  config: classpath:logback.xml