#记得要设置本目录为资源配置目录
server:
  port: 8112

spring:
  application:
    name: springcloud-service-external-users

#注册服务
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

#日志
logging:
  config: classpath:logback.xml