#记得要设置本目录为资源配置目录
server:
  port: 8221

spring:
  application:
    name: springcloud-ribbon-consumer

eureka:
  client:
    service-url:
      #注册服务地址
      defaultZone: http://localhost:8761/eureka/

#日志
logging:
  config: classpath:logback.xml

#设置断路器的超时（默认1s）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000